### ISSUE TITLE
Bug: 将 `using` 改为 `inject` 以消除 Koishi 4.15.2+ 中的警告

### ISSUE THREAD

**Issue by Lipraty** [koishijs/koishi-plugin-booru#104]
### Describe the bug

Koishi 4.15.2 及以上版本中会严格扫描依赖导入，且由于 TS 新关键字限制，会对使用 `using` 的插件抛出警告以敦促作者修改为新的 API：`inject`

### Steps to reproduce

-

### Expected behavior

使用 `inject` 导入依赖以消除警告

### Launcher

Koishi CLI (koishi start)

### Sources

Danbooru, Gelbooru, Konachan.com (NSFW), Konachan.net (SFW), Lolibooru, Lolicon, Pixiv, Safebooru, SankakuComplex, Yande.re

### Versions

-

### Additional context

在 peerDeps 中约束 Koishi 版本为 `^4.15.2`

**Comment by Lipraty** [comment]
booru-local 在本地有比较多的修改暂未 push，我会修改后 push。我顺便把其他的也改了？是提升 major 还是 minor 版本？

**Comment by MaikoTan** [comment]
I think you can just bump up the minor version in this case.

我想在这种情况下你可以把次要版本放大。

**Comment by Lipraty** [comment]
okay

**Comment by MaikoTan** [comment]
Lonay the Guru! :tada:
