### ISSUE TITLE
Feature: `spoiler` feature as an option

### ISSUE THREAD

**Issue by MaikoTan** [koishijs/koishi-plugin-booru#114]
> I think I could add the `spoiler` feature then, which would be implemented as forward messages on QQ.
>
>我想我可以添加“剧透”功能，该功能在QQ将作为转发消息实现。

_Originally posted by @MaikoTan in https://github.com/koishijs/koishi-plugin-booru/discussions/100#discussioncomment-7278426_

This can be implemented like:

```
spoiler:
  - disabled
  - all
  - only nsfw
```

**Comment by Lipraty** [comment]
Does a standard `Koishi` Element exist that aligns with this method? Like `<spoiler>`

**Comment by MaikoTan** [comment]
> Does a standard `Koishi` Element exist that aligns with this method? Like `<spoiler>`

Don't know if it is standard, but I saw telegram adapter support it.

https://github.com/satorijs/satori/blob/d1207d5ff77d9c877f6f938a27b16098c047e7bc/adapters/telegram/src/message.ts#L137

**Comment by Lipraty** [comment]
Koishi RFC: https://github.com/koishijs/koishi/issues/1258

Draft: https://github.com/koishijs/koishi-plugin-booru/pull/116

**Comment by MaikoTan** [comment]
Merged.
