### ISSUE TITLE
Bug: property booru is not registered, declare it as `inject` to suppress this warning

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi-plugin-booru#129]
### Describe the bug

![image](https://github.com/koishijs/koishi-plugin-booru/assets/96647698/0daf15ae-d360-425a-81af-9d37d57f7f32)

### Steps to reproduce

发送指令: `booru -c 2`

### Expected behavior

消除警告

### Launcher

Koishi CLI (koishi start)

### Sources

Lolicon

### Versions

- OS: Windows 11
- Adapter: Red
- Node version: 20.9.0
- Koishi version: 4.15.6

**Comment by idanran** [comment]
> What version of booru are you using?
> The `inject` was used in the very early on to eradicate this. And the change was released as version `1.1.0`.
> 
> For more information, look this: 
> https://github.com/koishijs/koishi-plugin-booru/blob/56168e9f22e5ebbf05f276f55e81ce00b0094d37/packages/core/src/index.tsx#L172-L175
> 
> You can also check out the commit: https://github.com/koishijs/koishi-plugin-booru/pull/106/commits/ec8e526c32884a1ebbead5f8a166731c2a63fea0
> And Issue: https://github.com/koishijs/koishi-plugin-booru/issues/104
> 
> Therefore, you need to upgrade to the latest version of `booru`.

Version 1.1.2

**Comment by Lipraty** [comment]
example:
```bash
yarn why koishi-plugin-booru
```

**Comment by idanran** [comment]
> example:
> 
> ```shell
> yarn why koishi-plugin-booru
> ```

![image](https://github.com/koishijs/koishi-plugin-booru/assets/96647698/ee183dff-d80a-4e57-8667-276f29bd146c)

**Comment by Kesunorin** [comment]
我也是这个问题，请问有解决方案吗？

**Comment by MaikoTan** [comment]
Is it resolved when you updated the `booru` plugin?

**Comment by Kesunorin** [comment]
我的情况也是和本issue一样的，Version 1.1.2，我使用`yarn why koishi-plugin-booru`查看确认过。
My situation is the same as this issue
`koishi-plugin-booru` Version: 1.1.2
I used 'yarn why koishi-plugin-booru' to check
**Version**
OS: Debian 12 (Termux Proot-distro)
Adapter: OneBot
Node version: 20.10.0
Koishi version: 4.16.0
**Sources**
Lolicon

**Comment by MaikoTan** [comment]
Well, we have just released the v1.1.3...

**Comment by Kesunorin** [comment]
对不起，我不知道这插件已经更新
Sorry, I didn't know that the plugin had been updated
现在已经解决了，谢谢！
and It has been resolved now,THNAKS!
