### ISSUE TITLE
Feature: get pixiv refresh token in configuration page

### ISSUE THREAD

**Issue by MaikoTan** [koishijs/koishi-plugin-booru#14]
### Sources

Pixiv

### Describe the problem related to the feature request

It is painful to get the refresh token before using the pixiv source plugin.

### Describe the solution you'd like

1. add a guide in the usage text
2. add login link in the page
3. investigate the oauth workflow, get `callback` and `code` from redirect.

Reference: https://gist.github.com/ZipFile/c9ebedb224406f4f11845ab700124362

**Comment by SaarChaffee** [comment]
we can use this plugin in the future！
[pixiv-auth](https://github.com/SaarChaffee/koishi-plugin-pixiv-auth.git)
