### ISSUE TITLE
Bug: konachan API encountered cloudflare blocking

### ISSUE THREAD

**Issue by saw71233** [koishijs/koishi-plugin-booru#161]
### Describe the bug

如标题，当发送/booru时报错

### Steps to reproduce

发送/booru时，插件报错

### Expected behavior

应正常运行并返回图片

### Screenshots

![Image_1710772548767](https://github.com/koishijs/koishi-plugin-booru/assets/115393808/58d8706a-422b-42d3-a18e-f48edae99022)
![Image_1710772553663](https://github.com/koishijs/koishi-plugin-booru/assets/115393808/2d8c0de2-b359-4062-b606-405ef8f52bfc)

### Launcher

Koishi Desktop

### Sources

E621 (and E926)

### Versions

- OS: Windows Server 2019
- Adapter: adapter-satori
- Node version: 18.12.0
- Koishi version: 4.17.x

**Comment by MaikoTan** [comment]
It should be fixed in the v1.1.7 version, no?

**Comment by saw71233** [comment]
well, that's my problem, i not use proxy.
but know i got a new question, use the booru-konachan got a cloudflare's verify
how i fix it?
![Image_1710808559963](https://github.com/koishijs/koishi-plugin-booru/assets/115393808/fc8f2fdf-8791-4d2d-87d8-1aa6dba4baf1)

**Comment by MaikoTan** [comment]
Are you using the credentials for the konachan plugin? If true, check whether your username or password is correctly configured; if false, try to set one.

Ref: https://booru.koishi.chat/zh-CN/plugins/konachan.html#keypairs

**Comment by saw71233** [comment]
okay, it not work, it's still blocked by cloudflare.

**Comment by MaikoTan** [comment]
Will you encounter the cloudflare while using a browser?

**Comment by saw71233** [comment]
yes

**Comment by MaikoTan** [comment]
It looks like `konachan.com` blocks any request from any client with cloudflare, but the safe site `konachan.net` should be still work. You can switch to it temporarily.

Since it is an upstream bug, we can't do anything for it.

**Comment by saw71233** [comment]
okay, thanks!
