### ISSUE TITLE
Bug: login与apikey必填却无用

### ISSUE THREAD

**Issue by medicago087** [koishijs/koishi-plugin-booru#17]
### Describe the bug

多数login和apikey目前无意义，建议删除

### Steps to reproduce

![image](https://user-images.githubusercontent.com/68104673/226543156-35e3fc9b-3bd7-4ee9-93a1-2ad215ceab9a.png)

### Expected behavior

删！

### Launcher

Koishi Desktop

### Sources

Danbooru, Gelbooru, Konachan.com (NSFW), Konachan.net (SFW), Lolibooru, Safebooru, Yande.re

### Versions

System:
    OS: Windows 10 10.0.19045
    CPU: (36) x64 Genuine Intel(R) CPU $0000%@

Binaries:
    Node: 16.17.0
    Yarn: 3.2.3

Koishi:
    Core: 4.12.1
    Console: 5.5.5
    Koishi Desktop: 0.9.2

**Comment by MaikoTan** [comment]
Fixed in #22
