### ISSUE TITLE
Bug: pixiv图源中的refresh token非必填，但缺失无法正常使用

### ISSUE THREAD

**Issue by medicago087** [koishijs/koishi-plugin-booru#19]
### Describe the bug

rt

### Steps to reproduce

空置refresh token，所有搜索结果报空

### Expected behavior

改为必填项

### Launcher

Koishi Desktop

### Sources

Pixiv

### Versions

System:
    OS: Windows 10 10.0.19045
    CPU: (36) x64 Genuine Intel(R) CPU $0000%@

Binaries:
    Node: 16.17.0
    Yarn: 3.2.3

Koishi:
    Core: 4.12.1
    Console: 5.5.5
    Koishi Desktop: 0.9.2

**Comment by MaikoTan** [comment]
fixed in #12
