### ISSUE TITLE
Feature: 增加图片微量修改，以免发不出造成retcode100

### ISSUE THREAD

**Issue by medicago087** [koishijs/koishi-plugin-booru#21]
### Sources

Danbooru, Gelbooru, Konachan.com (NSFW), Konachan.net (SFW), Lolibooru, Lolicon, Pixiv, Safebooru, Yande.re

### Describe the problem related to the feature request

nsfw或擦边图片极其容易被tx吞，若增加像素点微量修改则可以有效避免。

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/68104673/226544021-6391018a-46cc-4b49-8d2b-ae95885f15f8.png)
![image](https://user-images.githubusercontent.com/68104673/226543997-5c018caf-1d71-4275-b2a8-83f43d4a17fe.png)

**Comment by fatinghenji** [comment]
The same requirement, especially in the group chat call booru will give error code 100

**Comment by MaikoTan** [comment]
As Koishi no longer officially support `onebot` or `red`, we are not going to support this platform-specific feature, but it can still be implemented by other plugins:

```ts
ctx.before('send', (_, options) => {
  if (options?.session?.argv?.command?.name === 'booru') {
    session.elements = h.traverse(session.content, {
      image(val) {
        return change(val) // do some changes for the image
      },
    })
  }
})
```
