### ISSUE TITLE
Feature: clarify configurations for plugins

### ISSUE THREAD

**Issue by MaikoTan** [koishijs/koishi-plugin-booru#28]
### Sources

Danbooru, Gelbooru, Konachan.com (NSFW), Konachan.net (SFW), Lolibooru, Lolicon, Pixiv, Safebooru, Yande.re

### Describe the problem related to the feature request

Configurations should be clarified and classified into several sections.

### Describe the solution you'd like

```text
全局设置
|-- label
|-- weight
搜索设置
|-- ...
```

**Comment by shigma** [comment]
可以通过 `Schema.intersect()` 实现。
