### ISSUE TITLE
Bug: tokenize bug

### ISSUE THREAD

**Issue by Kabuda-czh** [koishijs/koishi-plugin-booru#39]
### Describe the bug

When `tokenize` is used, `command options` are invalid and are recognized as tags

### Steps to reproduce

use `booru blue archive, black dress -l gelbooru` or `booru blue archive, black dress, -l gelbooru`

The tag 👇
```ts
['blue_archive', 'black_dress', '-l_gelbooru']
```

### Expected behavior

Option and multitag can be used correctly

### Launcher

Koishi Desktop

### Sources

Danbooru, Gelbooru, Konachan.com (NSFW), Konachan.net (SFW), Lolibooru, Lolicon, Pixiv, Safebooru, Yande.re

### Versions

- OS: 
- Adapter: 
- Node version: 
- Koishi version:

**Comment by MaikoTan** [comment]
Well, just like novelai plugin, you should always append options BEFORE the query.

**Comment by Kabuda-czh** [comment]
> Well, just like novelai plugin, you should always append options BEFORE the query.

It's worked, maybe we should add hints or descriptions or examples to prompt user?
