### ISSUE TITLE
Feature: Add an option for image size

### ISSUE THREAD

**Issue by SaarChaffee** [koishijs/koishi-plugin-booru#68]
### Sources

Danbooru, Gelbooru, Konachan.com (NSFW), Konachan.net (SFW), Lolibooru, Lolicon, Pixiv, Safebooru, SankakuComplex, Yande.re

### Describe the problem related to the feature request

In some cases, downloading images for too long causes timeouts on the c-side.

### Describe the solution you'd like

Add an option for image size (if the source supports it).

**Comment by SaarChaffee** [comment]
![image](https://github.com/koishijs/koishi-plugin-booru/assets/53519746/53bbe0ea-f017-44ad-b382-ca16d7e797e7)

**Comment by Lipraty** [comment]
## Type

Define the image size type as follows:

- original
- large
- medium
- square

example:

```ts
export interface ImageSize {
  original: string
  large: string
  medium: string
  square: string
}
```

## Behavior

1. Managed and returned by the image source
2. Starting with 'original' and fallback from maximum size

example:

support(e.g. pixiv):
```ts
{
  original: 'https://i.pximg.net/[original link]',
  large: 'https://i.pximg.net/c/600x1200_90...',
  ...
}
```

unsupported:
```ts
{
  original: 'https://i.pximg.net/[original link]',
  large: 'https://i.pximg.net/[original link]',
  ...
}
```
